### ISSUE TITLE
Add students file for teacher_pets

### ISSUE THREAD

**Issue by rcliao** [csula/cs460-fall-2015#2]
In order to create sandbox environment for each student by themselves along, we will need to add students username one by one to a `student` file line by line.

This, in summary, will require each student to fill in their Github username in one file.

**Comment by rcliao** [comment]
John, can you request discount for this organization to have 30 private repositories here  -- https://education.github.com/discount_requests/new

**Comment by john-csula** [comment]
Hmm, did you request for something already?

![screen shot 2015-09-22 at 10 40 03 pm](https://cloud.githubusercontent.com/assets/13935369/10038428/ead8eea8-617a-11e5-8381-0785cbd7e4f2.png)

**Comment by rcliao** [comment]
Yeah, I requested already. It's pending state. Will let you know as soon as I got response back

**Comment by rcliao** [comment]
This is no longer needed because of http://classroom.github.com
