### ISSUE TITLE
Add Gitter for online chatroom

### ISSUE THREAD

**Issue by rcliao** [csula/cs460-fall-2015#3]
As named in title, we probably need a Gitter to improve communications between students and professors.

**Comment by rcliao** [comment]
Since I'm not owner to this repo, @john-csula Can you apply Gitter too?

**Comment by john-csula** [comment]
This done.  Here is the badge 

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/csula/cs460-fall-2015?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Please add this to `README.md`:

```
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/csula/cs460-fall-2015?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
```

**Comment by rcliao** [comment]
https://github.com/csula/cs460-fall-2015/pull/7 resolved
