### ISSUE TITLE
Update README.md with quick start guide section

### ISSUE THREAD

**Issue by john-csula** [csula/cs460-fall-2015#4]
Idea: most project (when first cloned), users can simply peruse the `README.md` file and get started without break a sweat.  This helps the impatience get started quickly.

Todo: add to the bottom of the `README.md` file with a quick start guide.  For example clone and type `gradle` -- done!

**Comment by rcliao** [comment]
Sounds perfect!

Will add a `Get started` section tonight.

**Comment by rcliao** [comment]
Resolved by 6693f89f916933a63b38eb62f155ff4ecdbf9e9c
