### ISSUE TITLE
Move CI badge to homework and project links?

### ISSUE THREAD

**Issue by john-csula** [csula/cs460-fall-2015#5]
Discussion: should we move the badge to each of the homework assignments (and project) link of the `README.md`?

![screenshot-csula-cs460-fall-2015 - mozilla firefox](https://cloud.githubusercontent.com/assets/13935369/9998072/777abf90-6044-11e5-90f8-85238de5d1ae.png)

**Comment by rcliao** [comment]
In regards of badge, it is showing if master branch is building or what not. I don't think this is valuable for homework by itself to see unless each homework is in a isolated branch.

**Comment by john-csula** [comment]
Then that begs the question should each assignment be a branch?  Maybe this is a better approach to consider?

**Comment by rcliao** [comment]
Please note that this badge is only for the latest commit in a specific branch (currently configured as master branch). Means this doesn't reflect anything in students repo/branch.

Eventually, the build result would be showing whenever they create Pull Request to this repo.

I'm thinking if there is anyway they can see per commit base; that would be way much helpful than this build badge.

In other word, this build badge is to showing coolness.

**Comment by john-csula** [comment]
Let's not do anything for now.  Doing less is doing more.  Or is it less is more?!?
